version: 2.1

executors:
  node-machine:
    working_directory: ~/repo
    docker:
      - image: circleci/node:7.10

jobs:
  checkout_code:
    executor: node-machine
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  deploy:
    executor: node-machine
    steps:
      - checkout

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
          filters:
            tags:
              only: /^\d{4}-\d{2}-\d{2}-v\d+$/
